### ISSUE TITLE
セキュリティの脆弱性

### ISSUE THREAD

**Issue by TakaShinoda** [TakaShinoda/beeenowiki#7]
Known high severity security vulnerability detected in lodash.template < 4.5.0 defined in yarn.lock.
yarn.lock update suggested: lodash.template ~> 4.5.0.

**Comment by otyaken** [comment]
これ自動でオープンした？

**Comment by korosuke613** [comment]
https://github.com/TakaShinoda/beeenowiki/commit/a1dfd966bf07150a01dec8738e12b5c5d9c1f895

なおしたビ

**Comment by TakaShinoda** [comment]
ありがとう！
おつびーの

**Comment by TakaShinoda** [comment]
ちなみにどうやってなおしたと？

**Comment by TakaShinoda** [comment]
yarn.lockをアップデートした感じ？

**Comment by korosuke613** [comment]
`yarn upgrade`ってコマンドうてばできる！

**Comment by TakaShinoda** [comment]
そうなんだ！
あざビーの😇
